[package]
name = "moor-compiler"
version = "0.9.0-alpha"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Functions and structures for compilation and decompilation of MOO source, including opcode declarations and builtin declarations"

[dev-dependencies]
pretty_assertions.workspace = true
test-case.workspace = true
unindent.workspace = true

[dependencies]
## Own
moor-common = { path = "../common" }
moor-var = { path = "../var" }

## General usefulness
bincode.workspace = true
byteview.workspace = true
itertools.workspace = true
lazy_static.workspace = true
strum.workspace = true

## Compiler grammar/parser
pest.workspace = true
pest_derive.workspace = true

## Error declaration/ handling
thiserror.workspace = true

## Logging & tracing
tracing.workspace = true
