[package]
name = "rpc-async-client"
version = "1.0.0-beta1"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Utilities for connection to the 0MQ RPC server via tokio/async calls"

[dependencies]
# Internal Dependencies
moor-common = { path = "../../common" }
moor-schema = { path = "../../schema" }
moor-var = { path = "../../var" }
rpc-common = { path = "../rpc-common" }

# Serialization & Data Formats
planus.workspace = true
serde.workspace = true
serde_json.workspace = true

# Networking & Communication
tmq.workspace = true
zmq.workspace = true

# Async Runtime & Concurrency
futures-util.workspace = true
tokio.workspace = true

# Authentication & Security
rusty_paseto.workspace = true

# Error Handling & Logging
eyre.workspace = true
thiserror.workspace = true
tracing.workspace = true

# Utilities & Helpers
chrono.workspace = true
hostname.workspace = true
uuid.workspace = true
