[package]
name = "moor-textdump"
version = "1.0.0-beta6"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
resolver = "2"
rust-version.workspace = true
description = "LambdaMOO compatible textdump parsing and generation for mooR."

[dev-dependencies]
moor-db = { path = "../db" }
similar-asserts.workspace = true

[dependencies]
# Internal Dependencies
moor-common = { path = "../common" }
moor-compiler = { path = "../compiler" }
moor-var = { path = "../var" }

# Serialization & Data Formats
base64.workspace = true
serde.workspace = true

# Text Processing & Regex
encoding_rs.workspace = true

# Error Handling & Logging
thiserror.workspace = true
tracing.workspace = true

# Utilities & Helpers
semver.workspace = true
strum.workspace = true
