[package]
name = "rpc-common"
version = "1.0.0-beta1"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Common entities used for 0MQ based RPC communication with the daemon."

[dependencies]
# Internal Dependencies
moor-common = { path = "../../common" }
moor-schema = { path = "../../schema" }
moor-var = { path = "../../var" }

# Command Line & Configuration
clap.workspace = true
clap_derive.workspace = true

# Serialization & Data Formats
byteview.workspace = true
planus.workspace = true
serde.workspace = true

# Authentication & Security
ed25519-dalek.workspace = true
rusty_paseto.workspace = true

# Error Handling
thiserror.workspace = true

# Utilities & Helpers
uuid.workspace = true
