[package]
name = "moor-db"
version = "0.9.0-alpha"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Interfaces for describing the worldstate of a moor database"

[dev-dependencies]
edn-format.workspace = true
eyre.workspace = true
tempfile.workspace = true

[dependencies]
## Own
moor-values = { path = "../common" }

## Error declaration/ handling
bytes.workspace = true
crossbeam-channel.workspace = true
fjall.workspace = true
indexmap.workspace = true
lazy_static.workspace = true
oneshot.workspace = true
rand.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true

[features]
relbox = []
